local map = vim.keymap.set

map("n", "<F9>",       function() require("dap").toggle_breakpoint() end, { desc = "Toggle breakpoint" })
map("n", "<F10>",      function() require("dap").step_over() end,         { desc = "Step over" })
map("n", "<F11>",      function() require("dap").step_into() end,         { desc = "Step into" })
map("n", "<F12>",      function() require("dap").continue() end,          { desc = "Continuar" })
map("n", "<leader>db", function() require("dap").toggle_breakpoint() end, { desc = "Toggle breakpoint" })
map("n", "<leader>dc", function() require("dap").continue() end,          { desc = "Continuar debugger" })
map("n", "<leader>do", function() require("dap").step_over() end,         { desc = "Step over" })
map("n", "<leader>di", function() require("dap").step_into() end,         { desc = "Step into" })
map("n", "<leader>dr", function() require("dap").repl.open() end,         { desc = "Abrir REPL" })
map("n", "<leader>du", function() require("dapui").toggle() end,          { desc = "Toggle DAP UI" })
map("n", "<leader>dB", function()
    require("dap").set_breakpoint(vim.fn.input("Condicion: "))
end, { desc = "Breakpoint condicional" })
