#! /bin/bash
pgrep -x sxhkd > /dev/null || sxhkd &
bspc monitor -d I II III IV V VI VII

bspc config border_width         2
bspc config window_gap          12
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# WALLPAPER ALEATORIO
WALLPAPER_DIR="/home/kali/.config/wallpapers"
N=$(( $(date +%N) % 4 + 1 ))
feh --bg-fill "$WALLPAPER_DIR/img$N.png"

# POLYBAR
sleep 1 && ~/.config/polybar/launch.sh &

# CUSTOM
bspc config focus_follows_pointer true

# BORDES
bspc config border_width         2
bspc config active_border_color  "#F4A7B9"
bspc config normal_border_color  "#3D3D3D"
bspc config focused_border_color "#F4A7B9"

# PICOM
picom --daemon

xsetroot -cursor_name left_ptr &
